apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: longhorn-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: longhorn
        meta.helm.sh/release-namespace: longhorn-system
      labels:
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/version: v1.4.2
        helm.sh/chart: longhorn-102.2.1_up1.4.2
      name: longhorn-service-account
      namespace: longhorn-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: longhorn
        meta.helm.sh/release-namespace: longhorn-system
      labels:
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/version: v1.4.2
        helm.sh/chart: longhorn-102.2.1_up1.4.2
      name: longhorn-support-bundle
      namespace: longhorn-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: nfs-subdir-external-provisioner
        meta.helm.sh/release-namespace: longhorn-system
      labels:
        app: nfs-subdir-external-provisioner
        app.kubernetes.io/managed-by: Helm
        chart: nfs-subdir-external-provisioner-4.0.18
        heritage: Helm
        release: nfs-subdir-external-provisioner
      name: nfs-subdir-external-provisioner
      namespace: longhorn-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations:
        meta.helm.sh/release-name: nfs-subdir-external-provisioner2
        meta.helm.sh/release-namespace: longhorn-system
      labels:
        app: nfs-subdir-external-provisioner
        app.kubernetes.io/managed-by: Helm
        chart: nfs-subdir-external-provisioner-4.0.18
        heritage: Helm
        release: nfs-subdir-external-provisioner2
      name: nfs-subdir-external-provisioner2
      namespace: longhorn-system
kind: List
metadata:
  resourceVersion: ""
