apiVersion: v1
items:
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"cdnnfs-storageclass"},"parameters":{"archiveOnDelete":"false"},"provisioner":"nfs-comimage","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
      name: cdnnfs-storageclass
    parameters:
      archiveOnDelete: "false"
    provisioner: nfs-comimage
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-storage"},"provisioner":"kubernetes.io/no-provisioner","volumeBindingMode":"WaitForFirstConsumer"}
      name: local-storage
    provisioner: kubernetes.io/no-provisioner
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        longhorn.io/last-applied-configmap: |
          kind: StorageClass
          apiVersion: storage.k8s.io/v1
          metadata:
            name: longhorn
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
          provisioner: driver.longhorn.io
          allowVolumeExpansion: true
          reclaimPolicy: "Delete"
          volumeBindingMode: Immediate
          parameters:
            numberOfReplicas: "3"
            staleReplicaTimeout: "30"
            fromBackup: ""
            fsType: "ext4"
            dataLocality: "disabled"
        storageclass.kubernetes.io/is-default-class: "true"
      name: longhorn
    parameters:
      dataLocality: disabled
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    provisioner: driver.longhorn.io
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      labels:
        cloudzdb.io/zdb-system: "true"
        purpose: backup
      name: longhorn-zdb-backup
    parameters:
      dataLocality: disabled
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    provisioner: driver.longhorn.io
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      labels:
        cloudzdb.io/zdb-system: "true"
        purpose: data
      name: longhorn-zdb-data
    parameters:
      dataLocality: disabled
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    provisioner: driver.longhorn.io
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"nfs-comimage"},"parameters":{"nfsPath":"/ec_comimage","nfsServer":"192.168.13.30"},"provisioner":"nfs-comimage","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}
      name: nfs-comimage
    parameters:
      nfsPath: /ec_comimage
      nfsServer: 192.168.13.30
    provisioner: nfs-comimage
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"nfs-custimage"},"parameters":{"nfsPath":"/ec_custimage","nfsServer":"192.168.13.30"},"provisioner":"nfs-custimage","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}
      name: nfs-custimage
    parameters:
      nfsPath: /ec_custimage
      nfsServer: 192.168.13.30
    provisioner: nfs-custimage
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"nfs-epfile-storageclass"},"parameters":{"archiveOnDelete":"false"},"provisioner":"nfs-epfile-provisioner","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
      name: nfs-epfile-storageclass
    parameters:
      archiveOnDelete: "false"
    provisioner: nfs-epfile-provisioner
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"nfs-storageclass"},"parameters":{"archiveOnDelete":"false"},"provisioner":"nfs-test","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
      name: nfs-storageclass
    parameters:
      archiveOnDelete: "false"
    provisioner: nfs-test
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"rook-ceph-block"},"parameters":{"dataLocality":"disabled","fromBackup":"","fsType":"ext4","numberOfReplicas":"3","staleReplicaTimeout":"30"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
      name: rook-ceph-block
    parameters:
      dataLocality: disabled
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    provisioner: driver.longhorn.io
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"rook-cephfs"},"parameters":{"dataLocality":"disabled","fromBackup":"","fsType":"ext4","numberOfReplicas":"3","staleReplicaTimeout":"30"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}
      name: rook-cephfs
    parameters:
      dataLocality: disabled
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    provisioner: driver.longhorn.io
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"rook-cephfs-zdb"},"parameters":{"dataLocality":"disabled","fromBackup":"","fsType":"ext4","numberOfReplicas":"3","staleReplicaTimeout":"30"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}
      name: rook-cephfs-zdb
    parameters:
      dataLocality: disabled
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    provisioner: driver.longhorn.io
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"rook-cephfs-zdb-backup"},"parameters":{"dataLocality":"disabled","fromBackup":"","fsType":"ext4","numberOfReplicas":"3","staleReplicaTimeout":"30"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Retain","volumeBindingMode":"Immediate"}
      name: rook-cephfs-zdb-backup
    parameters:
      dataLocality: disabled
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    provisioner: driver.longhorn.io
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
