apiVersion: v1
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        field.cattle.io/publicEndpoints: '[{"addresses":["172.21.9.11","172.21.9.12","172.21.9.13","172.21.9.21","172.21.9.22","172.21.9.23","172.21.9.31","172.21.9.32","172.21.9.33","172.21.9.41","172.21.9.42","172.21.9.43","172.21.9.51","172.21.9.52","172.21.9.61","172.21.9.62","172.21.9.63"],"port":80,"protocol":"HTTP","serviceName":"minio:minio-api-service","ingressName":"minio:api-server-ingress","hostname":"nsm-cloud-minio-api.nsmall.com","path":"/","allNodes":false}]'
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/backend-protocol":"HTTP","nginx.ingress.kubernetes.io/proxy-body-size":"0"},"name":"api-server-ingress","namespace":"minio"},"spec":{"rules":[{"host":"nsm-cloud-minio-newapi.nsmall.com","http":{"paths":[{"backend":{"service":{"name":"minio-api-service","port":{"number":9000}}},"path":"/","pathType":"Prefix"}]}}]}}
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      name: api-server-ingress
      namespace: minio
    spec:
      rules:
        - host: nsm-cloud-minio-api.nsmall.com
          http:
            paths:
              - backend:
                  service:
                    name: minio-api-service
                    port:
                      number: 9000
                path: /
                pathType: Prefix
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        field.cattle.io/publicEndpoints: '[{"addresses":["172.21.9.11","172.21.9.12","172.21.9.13","172.21.9.21","172.21.9.22","172.21.9.23","172.21.9.31","172.21.9.32","172.21.9.33","172.21.9.41","172.21.9.42","172.21.9.43","172.21.9.51","172.21.9.52","172.21.9.61","172.21.9.62","172.21.9.63"],"port":80,"protocol":"HTTP","serviceName":"minio:minio-service","ingressName":"minio:minio-server-ingress","hostname":"nsm-cloud-minio-s3.nsmall.com","path":"/","allNodes":false}]'
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/backend-protocol":"HTTP"},"name":"minio-server-ingress","namespace":"minio"},"spec":{"rules":[{"host":"nsm-cloud-newminio.nsmall.com","http":{"paths":[{"backend":{"service":{"name":"minio-service","port":{"number":9090}}},"path":"/","pathType":"Prefix"}]}}]}}
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      name: minio-server-ingress
      namespace: minio
    spec:
      rules:
        - host: nsm-cloud-minio-s3.nsmall.com
          http:
            paths:
              - backend:
                  service:
                    name: minio-service
                    port:
                      number: 9090
                path: /
                pathType: Prefix
kind: List
metadata:
  resourceVersion: ""
