apiVersion: v1
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"minio-pv-claim","namespace":"minio"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"40Gi"}}}}
        pv.kubernetes.io/bind-completed: "yes"
        pv.kubernetes.io/bound-by-controller: "yes"
        volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
        volume.kubernetes.io/storage-provisioner: driver.longhorn.io
      finalizers:
        - kubernetes.io/pvc-protection
      name: minio-pv-claim
      namespace: minio
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1073741824k
      storageClassName: longhorn
      volumeMode: Filesystem
      volumeName: pvc-af7a35e9-5eda-44b0-9db9-f9839366dc24
kind: List
metadata:
  resourceVersion: ""
